.TH qemu\-user\-static\ 1 2024-08-26 "9.0" Debian
.SH NAME
qemu\-user\-static\ \- QEMU User Emulator (compatibility symlink)
.SH DESCRIPTION
.B qemu\-user\-static
is a compatibility symlink for old qemu\-user\-static package
pointing to qemu\-user binary.
Please do not use these compatibility links, instead, switch to using
corresponding qemu\-user binaries (without the
.B \-static
suffix).
.SH SEE ALSO
.BR qemu-user (1)
.SH AUTHOR
This manual page was written by Michael Tokarev <mjt@tls.msk.ru>
